blog/urls.py
from django.urls import path
from blog.views import blog_page, detail_page, add_article, add_person, update_page, delete_page

app_name = 'blog'
urlpatterns = [
    path("main/", blog_page, name="blog_page"),
    path("detail/<int:article_id>/", detail_page, name="detail_page"),
    path("update/<int:article_id>/", update_page, name="update_page"),
    path("delete/<int:article_id>/", delete_page, name="delete_page"),
    path("article/", add_article, name="add_article"),
    path("person/", add_person, name="add_person"),
    # path("update/<int:pk>/", update_page, name="update_page"),
]

my_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls")),
    path('', include("home.urls")),
    path('accounts/', include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django_jalali.db import models as jmaodels


class Article(models.Model):

    title = models.CharField(max_length=250)
    text = models.TextField()
    created_date = jmaodels.jDateTimeField(auto_now_add=True)
    is_show = models.BooleanField(default=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/article/')

    def __str__(self):
        return self.title


class Person(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=200)
    age = models.IntegerField(help_text="کمک")
    email = models.EmailField(help_text="ایمیل")

    def __str__(self):
        res = self.first_name + " " + self.last_name
        return res

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django_jalali.forms import forms as jforms
from django.contrib.admin import widgets
from blog.models import Person

error_messages = {
    'required': "این فیلد الزامی است..."
}


class CreateArticle(forms.Form):
    title = forms.CharField(max_length=250, error_messages=error_messages, label="عنوان مقاله",
                            widget=forms.TextInput(attrs={'class': 'form-control'}))

    text = forms.CharField(max_length=650, error_messages=error_messages, widget=forms.Textarea(
        attrs={'class': "form-control"}), label="متن مقاله")

    created_date = forms.DateField(label="تاریخ", required=False, widget=forms.DateInput(
        attrs={'class': "form-control"}))

    is_show = forms.BooleanField(required=False,label="نمایش داده شود؟", error_messages=error_messages,
                                 widget=forms.CheckboxInput(attrs={'class': "form-check-input"}))

    image = forms.ImageField(label="عکس", error_messages=error_messages, widget=forms.FileInput(
        attrs={'class': "form-control"}))

    # author = forms.ModelChoiceField(queryset=User.objects.all(), error_messages=error_messages,
    #                                 widget=forms.Select(attrs={'class': "form-control"}))


class AddPerson(forms.Form):
    first_name = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': "form-control"}))
    last_name = forms.CharField(max_length=250, widget=forms.TextInput(attrs={'class': "form-control"}))
    age = forms.IntegerField(widget=forms.NumberInput(attrs={'class': "form-control"}))
    email = forms.EmailField(max_length=300, widget=forms.EmailInput(attrs={'class': "form-control"}))

class UpdateArticle(forms.Form):
    title = forms.CharField(max_length=250, error_messages=error_messages, label="عنوان مقاله",
                            widget=forms.TextInput(attrs={'class': 'form-control'}))

    text = forms.CharField(max_length=650, error_messages=error_messages, 
                           widget=forms.Textarea(attrs={'class': "form-control"}), label="متن مقاله")

    # created_date = forms.DateField(label="تاریخ", required=False, 
    #                                widget=forms.DateInput(attrs={'class': "form-control"}))

    is_show = forms.BooleanField(required=False,label="نمایش داده شود؟", error_messages=error_messages,
                                 widget=forms.CheckboxInput(attrs={'class': "form-check-input"}))

    image = forms.ImageField(label="عکس",required=False, error_messages=error_messages, 
                             widget=forms.FileInput(attrs={'class': "form-control"}))

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from blog.models import Article, Person
from blog.forms import CreateArticle, AddPerson, UpdateArticle
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


article_selected_id = 0

def blog_page(request):
    article = Article.objects.all()
    person = Person.objects.all()
    # print(article)
    # print(search_title)
    search_key = request.GET.get("search_title")
    print(request.GET.get('search_text'), 11)
    if search_key:
        article = article.filter(title__icontains=search_key)
        
    paginator = Paginator(article, 3)
    num_page = request.GET.get('page')
    page_obj = paginator.get_page(num_page)

    context = {
        'articles': page_obj,
        'persons': person,
        's_key': search_key,
    }
    return render(request, "blog/index.html", context)


def detail_page(request, article_id):
    if request.method == 'post':
        article_selected_id = request.POST.id
        
    a = get_object_or_404(Article, id=article_id)
    article_selected_id = article_id
    context = {
        'article': a,
    }
    return render(request, "blog/details.html", context)

@login_required
def add_article(request):
    if request.user.is_authenticated:
        print(request.method)
        if request.method == 'GET':
            form = CreateArticle()
        else:
            form = CreateArticle(data=request.POST, files=request.FILES)
            print(f"is valid: {form.is_valid()}")
            if form.is_valid():
                print(form.cleaned_data)
                article_title = form.cleaned_data.get('title')
                article_text = form.cleaned_data['text']
                article_created_date = form.cleaned_data['created_date']
                article_is_show = form.cleaned_data['is_show']
                article_image = form.cleaned_data['image']
                # article_author = form.cleaned_data['author']
                # item = Person.objects.get(pk=article_author)
                Article.objects.create(title=article_title,
                                       text=article_text, created_date=article_created_date,                                   is_show=article_is_show,
                                       image=article_image,
                                       author=request.user
                                    )
                a = Article.objects.last().pk
                print(f"last item is: {a}")
                return redirect('blog:detail_page', a)

        context = {
            'form': form,
        }
        return render(request, "blog/add_article.html", context)
    else:
        return redirect('accounts:login_page')

@login_required
def add_person(request):
    if request.method == 'GET':
        print(request.method)
        form_add = AddPerson()
    else:
        print(request.method)
        form_add = AddPerson(data=request.POST)
        if form_add.is_valid():
            print(f"is valid: {form_add.is_valid()}")
            print(form_add.cleaned_data)
            person_fname = form_add.cleaned_data.get('first_name')
            person_lname = form_add.cleaned_data.get('last_name')
            person_age = form_add.cleaned_data.get('age')
            person_email = form_add.cleaned_data.get('email')
            P = Person.objects.create(
                first_name=person_fname,
                last_name=person_lname,
                age=person_age,
                email=person_email
            )
            return redirect("blog:blog_page")

    return render(request, "blog/add_person.html", {'form': form_add})

@login_required
def update_page(request, article_id):
    record = get_object_or_404(Article, id=article_id)
    print(request.user.id)
    print(record.author.id)
    if request.user.id != record.author.id:
        return HttpResponse("page error...")
    if request.method == 'GET':
        print(record)
        article_form = UpdateArticle(initial={
            'title' : record.title,
            'text' : record.text,
            'created_date' : record.created_date,
            'is_show' : record.is_show,
            # 'imag' : record.image,
            })
    else:
        article_form = UpdateArticle(data=request.POST, files=request.FILES)
        if article_form.is_valid():
            title = article_form.cleaned_data.get('title')
            text = article_form.cleaned_data.get('text')
            # created_date = article_form.cleaned_data.get('created_date')
            is_show = article_form.cleaned_data.get('is_show')
            image = article_form.cleaned_data.get('image')
            
            record.title = title
            record.text = text
            # record.crated_date = created_date
            record.is_show = is_show
            if image:
                record.image = image
            
            record.save()
            
            return redirect('blog:detail_page', article_id)
    context = {'form' : article_form, 'edit' : record}
            
    return render(request, 'blog/edit_article.html', context)

@login_required
def delete_page(request, article_id):
    record = get_object_or_404(Article, pk=article_id)
    if request.user.id != record.author.id:
        return HttpResponse("page error...")
    record.delete()
    return redirect('blog:blog_page')

blog/templates/blog/add_article.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Created Form{% endblock title %}
{% block content %}
<div class="d-block text-bg-secondary text-end container ">
    <form action="{% url "blog:add_article" %}" method="post" class="m-1 p-3" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <div class="input-form a-title">
            <label for="{{ form.title.id_for_label}}" class="form-label">{{ form.title.label}}</label>
            {{ form.title }}
            {% for error in form.title.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-text">
            <label for="{{ form.text.id_for_label}}" class="form-label">{{ form.title.label}}</label>
            {{ form.text }}
            {% for error in form.text.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-date">
            <label for="id_created_date" class="form-label">تاریخ</label>
            {{ form.created_date }}
            {% for error in form.created_date.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-checkbox">
            <label for="id_is_show" class="form-label">نمایش داده شود؟</label>
            {{ form.is_show }}
            {% for error in form.is_show.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-imag">
            <label for="id_image" class="form-label">عکس مقاله</label>
            {{ form.image }}
            {% for error in form.image.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-author">
            <label for="id_author" class="form-label"> نویسنده</label>
            {{ form.author }}
            {% for error in form.author.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        {% comment %} {{form.errors}} {% endcomment %}
        <input type="submit" value="submit" class="btn bg-transparent border-primary border-3 hover d-block m-auto w-25">
    </form>
</div>
{% endblock content %}

blog/templates/blog/add_person.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Add Person{% endblock title %}
{% block content %}
    <div width="100%" class="bg-dark p-5">
        <div class="container text-bg-secondary mt-5">
            <form action="{% url "blog:add_person" %}" method="post" class="m-1 p-3">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="submit" class="btn bg-transparent border-primary border-3 hover d-block m-auto w-25 mt-5">
            </form>
        </div>
    </div>
{% endblock content %}

blog/templates/blog/details.html
{% extends "base/base.html" %}
{% block title %}{{article.title | capfirst}}{% endblock title %}
{% block main_header %}
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">مثال الألبوم</h1>
        <p class="lead text-body-secondary">وصف قصير حول الألبوم أدناه (محتوياته ، ومنشؤه ، وما إلى ذلك). اجعله قصير ولطيف، ولكن ليست قصير جدًا حتى لا يتخطى الناس هذا الألبوم تمامًا.</p>
        <p>
          <a href="{% url "blog:delete_page" article.id %}" class="btn btn-danger w-25 my-2">حذف</a>
          <a href="{% url "blog:update_page" article.id %}" class="btn btn-warning w-25 my-2">ویرایش</a>
        </p>
      </div>
    </div>
  </section>
{% endblock main_header %}
{% block content %}
  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row">
          <div class="card shadow-sm align-items-center">
            <img class="bd-placeholder-img text-center d-block object-fit-contain " width="50%" height="225" src="{{ article.image.url }}" ><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{article.title | capfirst}}</text>
            </img>
            <div class="card-body">
              <p class="card-text">این یک کارت گسترده تر با متن پشتیبانی در زیر به عنوان یک مقدمه طبیعی برای محتوای اضافی است. این محتوا کمی طولانی تر است.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  {% comment %} <a href="{% url "blog:article_edit" article_pk %}"> {% endcomment %}
                  <a href="{% url "blog:update_page" article.id %}">
                    <button type="button" class="btn btn-sm btn-outline-secondary">ویرایش</button>
                  </a>
                  <button type="button" class="btn btn-sm btn-outline-secondary">تعديل</button>
                </div>
                <small class="text-body-secondary">9 دقائق</small>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
{% endblock content %}

blog/templates/blog/edit_article.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Created Form{% endblock title %}
{% block content %}
<div class="d-block text-bg-secondary text-end container ">
    <form action="" method="post" class="m-1 p-3" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <div class="input-form a-title">
            <label for="{{ form.title.id_for_label}}" class="form-label">{{ form.title.label}}</label>
            {{ form.title }}
            {% for error in form.title.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="input-form a-text">
            <label for="{{ form.text.id_for_label}}" class="form-label">{{ form.title.label}}</label>
            {{ form.text }}
            {% for error in form.text.errors %}
                <smal class="text-warning fs-6">{{ error }}</smal>
            {% endfor %}
        </div>
        <div class="row mb-3">
            <div class="col">
                {% comment %} <div class="input-form a-date">
                    <label for="id_created_date" class="form-label">تاریخ</label>
                    {{ form.created_date }}
                    {% for error in form.created_date.errors %}
                        <smal class="text-warning fs-6">{{ error }}</smal>
                    {% endfor %}
                </div> {% endcomment %}
                <div class="input-form a-checkbox">
                    <label for="id_is_show" class="form-label">نمایش داده شود؟</label>
                    {{ form.is_show }}
                    {% for error in form.is_show.errors %}
                        <smal class="text-warning fs-6">{{ error }}</smal>
                    {% endfor %}
                </div>
            
                <div class="input-form a-imag col">
                    <label for="id_image" class="form-label"><a href="{{edit.image.url}}">عکس مقاله</a></label>
                    {{ form.image }}
                    {% for error in form.image.errors %}
                        <smal class="text-warning fs-6">{{ error }}</smal>
                    {% endfor %}
                </div>
            </div>
            <div class="col justify-content-center d-flex" >
                <img class="w-50" alt="{{ edit.image }}" src="{{ edit.image.url }}">
                {% for error in form.author.errors %}
                    <smal class="text-warning fs-6">{{ error }}</smal>
                {% endfor %}
            </div>
        </div>
        {% comment %} {{form.errors}} {% endcomment %}
        <input type="submit" value="Update" class="btn bg-transparent border-primary border-3 hover d-block m-auto w-25">
    </form>
</div>
{% endblock content %}

blog/templates/blog/index.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}Home page{% endblock title %}
{% block main_header %}
    {% include "base/main_header.html" %}
{% endblock main_header %}
{% block content %}
    {% comment %} <div>{{s_key}}</div> {% endcomment %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mb-5">
                {% for article in articles %}
                    <div class="card shadow-sm">
                        <a href="{% url "blog:detail_page" article.id %}">
                            <img class="bd-placeholder-img card-img-top" alt="" width="100%" height="225" src="{{ article.image.url }}">
                            <title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#55595c"/>
                            <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ article.title | capfirst }}</text>
                        </a>
                        <div class="card-body">
                            <p class="card-text">این یک کارت گسترده تر با متن پشتیبانی در زیر به عنوان یک مقدمه طبیعی
                                برای محتوای اضافی است. این محتوا کمی طولانی تر است.</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{% url "blog:update_page" article.id %}">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">ویرایش</button></a>
                                    <a href="{% url "blog:blog_page" %}">
                                    <button type="button" class="btn btn-sm btn-outline-secondary">حذف</button></a>
                                </div>
                                
                                    <small class="text-body-secondary">{{ article.author.get_full_name }}</small>
                                
                            </div>
                        </div>
                    </div>
                {% empty %}empty
                {% endfor %}
            </div>
            <nav aria-label="Page navigation example" class="mt-5" style="direction:ltr">
                <ul class="pagination justify-content-center">
                    {% if articles.has_previous %}
                        <li class="page-item">
                        <a class="page-link" href="?page=1">&laquo; first</a></li><li class="page-item">
                        <a class="page-link" href="?page={{ articles.previous_page_number }}"tabindex="-1">Previous</a>
                    {% comment %} {% else %}
                        <li class="page-item disabled">
                        <a class="page-link disabled" href="?page={{ articles.previous_page_number }}" {% endcomment %}
                    {% endif %}
                     
                    </li>
                    {% for p in articles.paginator.page_range %}
                        <li class="page-item {% if p == articles.number %} active {% endif %}">
                            <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                        </li>
                    {% endfor %}
                    {% if articles.has_next %}
                        <li class="page-item">
                        <a class="page-link" href="?page={{ articles.next_page_number }}">Next</a></li><li class="page-item">
                        <a class="page-link" href="?page={{ articles.paginator.num_pages }}">last &raquo;</a>
                    {% comment %} {% else %}
                        <li class="page-item disabled">
                        <a class="page-link disabled" href="?page={{ articles.next_page_number }}">Next</a> {% endcomment %}
                    {% endif %}
                    
                    </li>
                </ul>
            </nav>
        </div>
    </div>
{% endblock content %}